---
Name: grid-field-styling
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'xddesigners/grid-field-styling:client/dist/styles/grid-field-styling.css'
  extensions:
    - XD\GridFieldStyling\Extensions\LeftAndMainExtension
SilverStripe\Forms\GridField\GridField:
  extensions:
    - XD\GridFieldStyling\Extensions\GridFieldExtension
